2024-12-12 01:14:09 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:14:09 --> INFO: logging in using static token
2024-12-12 01:14:11 --> INFO: Shard ID None has connected to Gateway (Session ID: 60cd4f3c1de8c1cf3259c9307698eb6a).
2024-12-12 01:14:13 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:14:13 --> INFO: 伺服器狀態更新為: GO了10次 | 1 個伺服器
2024-12-12 01:14:38 --> INFO: 伺服器ID: 762279698360172595 台詞: 好棒喔 耗時: 3.093 秒
2024-12-12 01:14:55 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 163, in mygo
    frame_number = frame_number + back_frames + 15
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:17:49 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:17:49 --> INFO: logging in using static token
2024-12-12 01:17:51 --> INFO: Shard ID None has connected to Gateway (Session ID: e44f49fa61fc29349e2b1f2da6336c07).
2024-12-12 01:17:54 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:17:54 --> INFO: 伺服器狀態更新為: GO了11次 | 1 個伺服器
2024-12-12 01:17:56 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 164, in mygo
    frame_number = frame_number + back_frames + 15
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:18:16 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:18:16 --> INFO: logging in using static token
2024-12-12 01:18:18 --> INFO: Shard ID None has connected to Gateway (Session ID: a75d75981292810631e2e3bb158fd3ed).
2024-12-12 01:18:26 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 165, in mygo
    frame_number = frame_number + back_frames + 15
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:18:44 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:18:44 --> INFO: logging in using static token
2024-12-12 01:18:46 --> INFO: Shard ID None has connected to Gateway (Session ID: 55a980e0be14c2d8b0018b2426533baa).
2024-12-12 01:18:50 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 165, in mygo
    frame_number = frame_number + back_frames + 15
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:19:24 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:19:24 --> INFO: 伺服器狀態更新為: GO了11次 | 1 個伺服器
2024-12-12 01:21:21 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 165, in mygo
    back_frames = second * 23.98
                   ~~~~~~^~~~~~
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:22:29 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:22:29 --> INFO: logging in using static token
2024-12-12 01:22:31 --> INFO: Shard ID None has connected to Gateway (Session ID: b9f2f401192c8965cf8c7edbbf91f483).
2024-12-12 01:22:33 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:22:33 --> INFO: 伺服器狀態更新為: GO了11次 | 1 個伺服器
2024-12-12 01:22:54 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 166, in mygo
    frame_number = frame_number + back_frames + 15
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: UnboundLocalError: cannot access local variable 'frame_number' where it is not associated with a value
2024-12-12 01:23:21 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:23:21 --> INFO: logging in using static token
2024-12-12 01:23:23 --> INFO: Shard ID None has connected to Gateway (Session ID: 82904390b003f3d3633cf54add4d780a).
2024-12-12 01:23:26 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:23:26 --> INFO: 伺服器狀態更新為: GO了11次 | 1 個伺服器
2024-12-12 01:23:46 --> INFO: 伺服器ID: 762279698360172595 台詞: 好棒喔 耗時: 4.128 秒
2024-12-12 01:25:19 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 01:25:19 --> INFO: logging in using static token
2024-12-12 01:25:21 --> INFO: Shard ID None has connected to Gateway (Session ID: 12acce620c9fd7d7dd15610bb076cc16).
2024-12-12 01:25:24 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 01:25:24 --> INFO: 伺服器狀態更新為: GO了12次 | 1 個伺服器
2024-12-12 01:25:38 --> INFO: 伺服器ID: 762279698360172595 台詞: 好棒喔 1.5秒GIF耗時: 3.979 秒
2024-12-12 10:20:41 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:20:41 --> INFO: logging in using static token
2024-12-12 10:20:43 --> INFO: Shard ID None has connected to Gateway (Session ID: 5b287e8c92e02b0de4b1fd73b494b5ad).
2024-12-12 10:20:46 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:20:46 --> INFO: 伺服器狀態更新為: GO了13次 | 1 個伺服器
2024-12-12 10:21:14 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 5.509 秒
2024-12-12 10:21:30 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:21:30 --> INFO: logging in using static token
2024-12-12 10:21:31 --> INFO: Shard ID None has connected to Gateway (Session ID: aa9840f60ef5a460c0f596c69fdc6bae).
2024-12-12 10:21:34 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:21:34 --> INFO: 伺服器狀態更新為: GO了14次 | 1 個伺服器
2024-12-12 10:21:40 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 4.016 秒
2024-12-12 10:21:52 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼要演奏春日影! 耗時: 1.584 秒
2024-12-12 10:22:01 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:22:01 --> INFO: logging in using static token
2024-12-12 10:22:03 --> INFO: Shard ID None has connected to Gateway (Session ID: 48d53c31351a87d977d2bfc54e5b3148).
2024-12-12 10:22:05 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:22:05 --> INFO: 伺服器狀態更新為: GO了16次 | 1 個伺服器
2024-12-12 10:22:43 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼要演奏春日影! 耗時: 2.565 秒
2024-12-12 10:22:58 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 4.229 秒
2024-12-12 10:23:10 --> INFO: 伺服器ID: 762279698360172595 台詞: 味道醇香,我很喜歡 耗時: 4.335 秒
2024-12-12 10:23:24 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:23:24 --> INFO: logging in using static token
2024-12-12 10:23:25 --> INFO: Shard ID None has connected to Gateway (Session ID: 1c59f7abaf3b68d1c42303e313f12ead).
2024-12-12 10:23:28 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:23:28 --> INFO: 伺服器狀態更新為: GO了19次 | 1 個伺服器
2024-12-12 10:23:37 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 4.345 秒
2024-12-12 10:23:50 --> INFO: 伺服器ID: 762279698360172595 台詞: 味道醇香,我很喜歡 耗時: 6.008 秒
2024-12-12 10:26:35 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:26:35 --> INFO: logging in using static token
2024-12-12 10:26:36 --> INFO: Shard ID None has connected to Gateway (Session ID: 4d34d192a2168b6ab797a153b1091caa).
2024-12-12 10:26:39 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:26:39 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 10:27:35 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:27:35 --> INFO: logging in using static token
2024-12-12 10:27:37 --> INFO: Shard ID None has connected to Gateway (Session ID: afdaf5baa530124c139b0936a43b1ede).
2024-12-12 10:27:39 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:27:39 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 10:28:41 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 10:28:41 --> INFO: logging in using static token
2024-12-12 10:28:43 --> INFO: Shard ID None has connected to Gateway (Session ID: a5f66a02299a311a218edcc8a2d223ae).
2024-12-12 10:28:45 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 10:28:45 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:10:38 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:10:38 --> INFO: logging in using static token
2024-12-12 15:10:41 --> INFO: Shard ID None has connected to Gateway (Session ID: 4795ac7b91a89b65a899a6f6cc18f1f9).
2024-12-12 15:10:43 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:10:43 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:11:00 --> INFO: 2024-12-12 15:11:00-->伺服器ID: 762279698360172595 未找到台詞{'text': '為什麼要演奏春日影!', 'episode': '7', 'frame_start': 30124, 'frame_end': 30168}
2024-12-12 15:18:20 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:18:20 --> INFO: logging in using static token
2024-12-12 15:18:22 --> INFO: Shard ID None has connected to Gateway (Session ID: e730889cfd545f1fed59c3f8c6b12598).
2024-12-12 15:18:25 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:18:25 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:20:24 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:20:24 --> INFO: logging in using static token
2024-12-12 15:20:26 --> INFO: Shard ID None has connected to Gateway (Session ID: 1474b83af474daa48dce343ff1a63498).
2024-12-12 15:20:28 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:20:28 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:22:30 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:22:30 --> INFO: logging in using static token
2024-12-12 15:22:31 --> INFO: Shard ID None has connected to Gateway (Session ID: 6c3876512e799561c7a22b85b2d06973).
2024-12-12 15:22:34 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:22:34 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:23:56 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:23:56 --> INFO: logging in using static token
2024-12-12 15:23:58 --> INFO: Shard ID None has connected to Gateway (Session ID: ac677e09bbe5662a11d5d8b06106fa2a).
2024-12-12 15:24:00 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:24:00 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:25:37 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:25:37 --> INFO: logging in using static token
2024-12-12 15:25:39 --> INFO: Shard ID None has connected to Gateway (Session ID: f85cf6ee28b7aeeab6653e08d302ad2d).
2024-12-12 15:25:42 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:25:42 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:26:01 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 166, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 78, in text_process_precise
    if text['text'].lower() == item['text'].lower() and len(item['text']) < 100 and item['frame_start'] == text['frame_start']:
       ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 15:30:35 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:30:35 --> INFO: logging in using static token
2024-12-12 15:30:37 --> INFO: Shard ID None has connected to Gateway (Session ID: aa00d0199e5997ae598de09eba0fd27a).
2024-12-12 15:30:40 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:30:40 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:30:59 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:30:59 --> INFO: logging in using static token
2024-12-12 15:31:01 --> INFO: Shard ID None has connected to Gateway (Session ID: 6d33061720e435da7e3ead3cc59d85eb).
2024-12-12 15:31:40 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:31:40 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:32:00 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:32:00 --> INFO: logging in using static token
2024-12-12 15:32:02 --> INFO: Shard ID None has connected to Gateway (Session ID: dd62a23f79a5eff8a45f52a199c9993b).
2024-12-12 15:32:04 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:32:04 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:32:34 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:32:34 --> INFO: logging in using static token
2024-12-12 15:32:36 --> INFO: Shard ID None has connected to Gateway (Session ID: cc0e460d2d2691ba2d85208cc74f7b65).
2024-12-12 15:32:38 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:32:38 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:33:22 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:33:22 --> INFO: logging in using static token
2024-12-12 15:33:23 --> INFO: Shard ID None has connected to Gateway (Session ID: e3008687bcbbd8bc7c12df8e4db120de).
2024-12-12 15:33:26 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:33:26 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:35:49 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:35:49 --> INFO: logging in using static token
2024-12-12 15:35:51 --> INFO: Shard ID None has connected to Gateway (Session ID: d5ca45821c0c863be61a5d0a35a14c95).
2024-12-12 15:35:54 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:35:54 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:36:28 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:36:28 --> INFO: logging in using static token
2024-12-12 15:36:30 --> INFO: Shard ID None has connected to Gateway (Session ID: 929d9c3b0e2b613589f52e1964c2b9fa).
2024-12-12 15:36:33 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:36:33 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:40:28 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:40:28 --> INFO: logging in using static token
2024-12-12 15:40:30 --> INFO: Shard ID None has connected to Gateway (Session ID: 26c1f7782db084f7094ffe2737544815).
2024-12-12 15:40:32 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:40:32 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:42:08 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:42:08 --> INFO: logging in using static token
2024-12-12 15:42:10 --> INFO: Shard ID None has connected to Gateway (Session ID: c31965538dc40cf723365bc47d7050b6).
2024-12-12 15:44:20 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:44:20 --> INFO: logging in using static token
2024-12-12 15:44:35 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:44:35 --> INFO: logging in using static token
2024-12-12 15:44:37 --> INFO: Shard ID None has connected to Gateway (Session ID: 644ab46a4d95d5788228032544bb1e35).
2024-12-12 15:44:39 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:44:39 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:46:32 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:46:32 --> INFO: logging in using static token
2024-12-12 15:46:34 --> INFO: Shard ID None has connected to Gateway (Session ID: cf9e145f98ce1e5f0344dfc9e626c065).
2024-12-12 15:46:37 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:46:37 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:46:42 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 167, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 77, in text_process_precise
    if item['text'] == text['text'] and item['frame_start'] == text['frame_start']:
                       ~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: string indices must be integers, not 'str'
2024-12-12 15:47:12 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:47:12 --> INFO: logging in using static token
2024-12-12 15:47:13 --> INFO: Shard ID None has connected to Gateway (Session ID: 47540569a71ac95079351d6ba602fc25).
2024-12-12 15:47:16 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:47:16 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:47:20 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 167, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 77, in text_process_precise
    if item['text'] == text['text'] and item['frame_start'] == text['frame_start']:
                       ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 15:48:10 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:48:10 --> INFO: logging in using static token
2024-12-12 15:48:12 --> INFO: Shard ID None has connected to Gateway (Session ID: b30309f680d1e8f169e8b1b220762eea).
2024-12-12 15:48:14 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:48:14 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:49:40 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:49:40 --> INFO: logging in using static token
2024-12-12 15:49:42 --> INFO: Shard ID None has connected to Gateway (Session ID: ca5323a7ac1631e454baaebe1d81a385).
2024-12-12 15:49:44 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:49:44 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:52:37 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:52:37 --> INFO: logging in using static token
2024-12-12 15:52:39 --> INFO: Shard ID None has connected to Gateway (Session ID: 942f9603b79593f1912e196d6c1b2a0b).
2024-12-12 15:52:42 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:52:42 --> INFO: 伺服器狀態更新為: GO了21次 | 1 個伺服器
2024-12-12 15:52:48 --> INFO: 伺服器ID: 762279698360172595 台詞: {"text": "為什麼要演奏春日影!", "episode": "7", "frame_start": 30124, "frame_end": 30168} 耗時: 2.534 秒
2024-12-12 15:53:10 --> INFO: 伺服器ID: 762279698360172595 台詞: {"text": "好棒喔", "episode": "1-3", "frame_start": 55328, "frame_end": 55352} 耗時: 2.859 秒
2024-12-12 15:53:44 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:53:44 --> INFO: logging in using static token
2024-12-12 15:53:46 --> INFO: Shard ID None has connected to Gateway (Session ID: 3d611c221e67cb38ed8386524bb4e883).
2024-12-12 15:53:48 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:53:48 --> INFO: 伺服器狀態更新為: GO了23次 | 1 個伺服器
2024-12-12 15:53:55 --> INFO: 伺服器ID: 762279698360172595 台詞: {"text": "好棒喔", "episode": "1-3", "frame_start": 55328, "frame_end": 55352} 耗時: 2.878 秒
2024-12-12 15:58:57 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 15:58:57 --> INFO: logging in using static token
2024-12-12 15:58:59 --> INFO: Shard ID None has connected to Gateway (Session ID: 2b0c0145fc02bd0b9e3640a970987382).
2024-12-12 15:59:01 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 15:59:01 --> INFO: 伺服器狀態更新為: GO了24次 | 1 個伺服器
2024-12-12 15:59:59 --> INFO: Shard ID None has successfully RESUMED session 2b0c0145fc02bd0b9e3640a970987382.
2024-12-12 16:01:30 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 172, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 77, in text_process_precise
    if item['text'] == text['text'] and item['frame_start'] == text['frame_start']:
                       ~~~~^^^^^^^^
KeyError: 'text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: KeyError: 'text'
2024-12-12 16:02:01 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 16:02:01 --> INFO: logging in using static token
2024-12-12 16:02:03 --> INFO: Shard ID None has connected to Gateway (Session ID: 3b36c51bf85d457ce3bc7f176a045e3c).
2024-12-12 16:02:05 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 16:02:05 --> INFO: 伺服器狀態更新為: GO了24次 | 1 個伺服器
2024-12-12 16:02:22 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 3.284 秒
2024-12-12 16:02:38 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 3.621 秒
2024-12-12 16:04:40 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 16:04:40 --> INFO: logging in using static token
2024-12-12 16:04:42 --> INFO: Shard ID None has connected to Gateway (Session ID: b56cf4796d9fc20adfcee961ca129ab9).
2024-12-12 16:04:45 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 16:04:45 --> INFO: 伺服器狀態更新為: GO了26次 | 1 個伺服器
2024-12-12 16:06:14 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 16:06:14 --> INFO: logging in using static token
2024-12-12 16:06:15 --> INFO: Shard ID None has connected to Gateway (Session ID: 65bc1ce6d1b040e1c21c2f1b00d76bed).
2024-12-12 16:06:18 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 16:06:18 --> INFO: 伺服器狀態更新為: GO了26次 | 1 個伺服器
2024-12-12 16:06:39 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 3.488 秒
2024-12-12 16:07:03 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 7.529 秒
2024-12-12 16:08:25 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 16:08:25 --> INFO: logging in using static token
2024-12-12 16:08:27 --> INFO: Shard ID None has connected to Gateway (Session ID: 84e2accde55138bca687ff04a63c9722).
2024-12-12 16:08:30 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 16:08:30 --> INFO: 伺服器狀態更新為: GO了28次 | 1 個伺服器
2024-12-12 16:09:49 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 4.186 秒
2024-12-12 16:13:22 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 16:13:22 --> INFO: logging in using static token
2024-12-12 16:13:24 --> INFO: Shard ID None has connected to Gateway (Session ID: d809fa3611ccc5df3b9e3b854a4f1dd0).
2024-12-12 16:13:27 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 16:13:27 --> INFO: 伺服器狀態更新為: GO了29次 | 1 個伺服器
2024-12-12 16:14:05 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 14568, "frame_end": 14592, "episode": "10"} 耗時: 3.636 秒
2024-12-12 19:09:13 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:09:13 --> INFO: logging in using static token
2024-12-12 19:09:15 --> INFO: Shard ID None has connected to Gateway (Session ID: 0a93e3f6e16c39fa607b0d44c8a002e9).
2024-12-12 19:09:18 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:09:18 --> INFO: 伺服器狀態更新為: GO了30次 | 1 個伺服器
2024-12-12 19:10:51 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:10:51 --> INFO: logging in using static token
2024-12-12 19:10:52 --> INFO: Shard ID None has connected to Gateway (Session ID: 927782938a4b2b5f0ec77afac7fbd061).
2024-12-12 19:10:55 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:10:55 --> INFO: 伺服器狀態更新為: GO了30次 | 1 個伺服器
2024-12-12 19:11:36 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 94808, "frame_end": 94824, "episode": "1-3"} 耗時: 3.501 秒
2024-12-12 19:12:40 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:12:40 --> INFO: logging in using static token
2024-12-12 19:12:42 --> INFO: Shard ID None has connected to Gateway (Session ID: bf5e1f3cb5db6adc5b21e709b43319ff).
2024-12-12 19:12:44 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:12:44 --> INFO: 伺服器狀態更新為: GO了31次 | 1 個伺服器
2024-12-12 19:13:02 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 94808, "frame_end": 94824, "episode": "1-3"} 耗時: 10.083 秒
2024-12-12 19:13:35 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:13:35 --> INFO: logging in using static token
2024-12-12 19:13:37 --> INFO: Shard ID None has connected to Gateway (Session ID: a73397eebe079b455281e6a62148ca02).
2024-12-12 19:13:39 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:13:39 --> INFO: 伺服器狀態更新為: GO了32次 | 1 個伺服器
2024-12-12 19:13:53 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 94808, "frame_end": 94824, "episode": "1-3"} 耗時: 7.537 秒
2024-12-12 19:14:11 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 43136, "frame_end": 43136, "episode": "1-3"} 耗時: 7.083 秒
2024-12-12 19:14:52 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 18904, "frame_end": 18944, "episode": "1-3"} 耗時: 7.268 秒
2024-12-12 19:15:09 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 6208, "frame_end": 6208, "episode": "9"} 耗時: 5.455 秒
2024-12-12 19:15:24 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 45832, "frame_end": 45856, "episode": "1-3"} 耗時: 6.364 秒
2024-12-12 19:15:46 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 55328, "frame_end": 55352, "episode": "1-3"} 耗時: 4.777 秒
2024-12-12 19:16:01 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 10808, "frame_end": 10816, "episode": "1-3"} 耗時: 4.226 秒
2024-12-12 19:16:11 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 6616, "frame_end": 6632, "episode": "12"} 耗時: 3.833 秒
2024-12-12 19:16:47 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 47592, "frame_end": 47632, "episode": "1-3"} 耗時: 5.007 秒
2024-12-12 19:17:28 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 189, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 73, in text_process_precise
    text = json.loads(text)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-12-12 19:17:47 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 5256, "frame_end": 5272, "episode": "7"} 耗時: 5.943 秒
2024-12-12 19:18:02 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 3592, "frame_end": 3616, "episode": "1-3"} 耗時: 5.324 秒
2024-12-12 19:18:31 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 7680, "frame_end": 7696, "episode": "11"} 耗時: 5.980 秒
2024-12-12 19:18:50 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 4160, "frame_end": 4184, "episode": "13"} 耗時: 5.701 秒
2024-12-12 19:19:04 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 23504, "frame_end": 23536, "episode": "10"} 耗時: 6.217 秒
2024-12-12 19:20:56 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:20:56 --> INFO: logging in using static token
2024-12-12 19:20:58 --> INFO: Shard ID None has connected to Gateway (Session ID: ef30fb3cf8b4283d2a987be2aec86b3a).
2024-12-12 19:21:01 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:21:01 --> INFO: 伺服器狀態更新為: GO了46次 | 1 個伺服器
2024-12-12 19:21:12 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 1120, "frame_end": 1192, "episode": "1-3"} 耗時: 6.759 秒
2024-12-12 19:21:53 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:21:53 --> INFO: logging in using static token
2024-12-12 19:21:55 --> INFO: Shard ID None has connected to Gateway (Session ID: 13d794963cb8b7be85d86a9a4e297180).
2024-12-12 19:21:58 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:21:58 --> INFO: 伺服器狀態更新為: GO了47次 | 1 個伺服器
2024-12-12 19:22:22 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 1584, "frame_end": 1632, "episode": "1-3"} 耗時: 3.444 秒
2024-12-12 19:22:37 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 188, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 77, in text_process_precise
    if item['episode'] == text['episode'] and item['frame_start'] == text['frame_start']:
                          ~~~~^^^^^^^^^^^
TypeError: 'int' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: 'int' object is not subscriptable
2024-12-12 19:23:20 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:23:20 --> INFO: logging in using static token
2024-12-12 19:23:22 --> INFO: Shard ID None has connected to Gateway (Session ID: 01ff76da021e323bd2de8b8eaf86d228).
2024-12-12 19:23:25 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:23:25 --> INFO: 伺服器狀態更新為: GO了48次 | 1 個伺服器
2024-12-12 19:23:25 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 191, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 78, in text_process_precise
    if item['episode'] == text['episode'] and item['frame_start'] == text['frame_start']:
                          ~~~~^^^^^^^^^^^
TypeError: 'int' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: 'int' object is not subscriptable
2024-12-12 19:23:39 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:23:39 --> INFO: logging in using static token
2024-12-12 19:23:41 --> INFO: Shard ID None has connected to Gateway (Session ID: 52254495d2de5165b0196cebb1dac31f).
2024-12-12 19:24:24 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:24:24 --> INFO: 伺服器狀態更新為: GO了48次 | 1 個伺服器
2024-12-12 19:28:40 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:28:40 --> INFO: logging in using static token
2024-12-12 19:28:42 --> INFO: Shard ID None has connected to Gateway (Session ID: a6f0cfa8fae7acc6d3b09ac626ad5ba8).
2024-12-12 19:28:45 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:28:45 --> INFO: 伺服器狀態更新為: GO了49次 | 1 個伺服器
2024-12-12 19:29:05 --> INFO: 伺服器ID: 762279698360172595 台詞: {"frame_start": 80, "frame_end": 88, "episode": "12"} 耗時: 10.004 秒
2024-12-12 19:30:15 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:30:15 --> INFO: logging in using static token
2024-12-12 19:30:17 --> INFO: Shard ID None has connected to Gateway (Session ID: 75b129a1ccd33d1a097a674f3b413814).
2024-12-12 19:30:20 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:30:20 --> INFO: 伺服器狀態更新為: GO了51次 | 1 個伺服器
2024-12-12 19:30:38 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 221, in mygo
    logging.info(f"伺服器ID: {interaction.guild_id} 台詞: {result['text']} 耗時: {total_seconds:.3f} 秒")
                                                           ~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 19:32:00 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:32:00 --> INFO: logging in using static token
2024-12-12 19:32:02 --> INFO: Shard ID None has connected to Gateway (Session ID: 7640ab2dfe33adc93449e0d373a2ab6d).
2024-12-12 19:32:04 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:32:04 --> INFO: 伺服器狀態更新為: GO了52次 | 1 個伺服器
2024-12-12 19:32:20 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 10.535 秒
2024-12-12 19:34:55 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:34:55 --> INFO: logging in using static token
2024-12-12 19:34:57 --> INFO: Shard ID None has connected to Gateway (Session ID: 9932f1736fac5810cc98d858a2961388).
2024-12-12 19:35:00 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:35:00 --> ERROR: Unhandled exception in internal background task 'update_status'.
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 47, in update_status
    record(None)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 154, in record
    new_record = {"text": text['text'], "episode": text['episode'], "frame_start": text['frame_start'], "frame_end": text['frame_end'], "times": 1}
                          ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-12-12 19:35:36 --> ERROR: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Loop._loop() done, defined at C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py:200> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 264, in _loop
    raise exc
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 47, in update_status
    record(None)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 154, in record
    new_record = {"text": text['text'], "episode": text['episode'], "frame_start": text['frame_start'], "frame_end": text['frame_end'], "times": 1}
                          ^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-12-12 19:35:37 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:35:37 --> INFO: logging in using static token
2024-12-12 19:35:38 --> INFO: Shard ID None has connected to Gateway (Session ID: c56f135fbe7765db94c9edce8273d11a).
2024-12-12 19:35:41 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:35:41 --> ERROR: Unhandled exception in internal background task 'update_status'.
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 47, in update_status
    record(None)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 150, in record
    if item['text'] == text['text'] and item['episode'] == text['episode'] and item['frame_start'] == text['frame_start']:
                       ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-12-12 19:36:27 --> ERROR: Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Loop._loop() done, defined at C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py:200> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 264, in _loop
    raise exc
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\ext\tasks\__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 47, in update_status
    record(None)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 150, in record
    for item in data['title']:
                           ^^^^
TypeError: 'NoneType' object is not subscriptable
2024-12-12 19:36:27 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:36:27 --> INFO: logging in using static token
2024-12-12 19:36:29 --> INFO: Shard ID None has connected to Gateway (Session ID: d4a5585fbe35cf7281cf8eae35757618).
2024-12-12 19:36:32 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:36:32 --> INFO: 伺服器狀態更新為: GO了53次 | 1 個伺服器
2024-12-12 19:36:48 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 4.338 秒
2024-12-12 19:36:48 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 223, in mygo
    record(result)
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 151, in record
    if item['text'] == text['text'] and item['episode'] == text['episode'] and item['frame_start'] == text['frame_start']:
                       ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 19:37:41 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:37:41 --> INFO: logging in using static token
2024-12-12 19:37:43 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:37:43 --> INFO: logging in using static token
2024-12-12 19:37:45 --> INFO: Shard ID None has connected to Gateway (Session ID: cf7e04910a4e96504e1d332da88d4867).
2024-12-12 19:37:47 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:37:47 --> INFO: 伺服器狀態更新為: GO了53次 | 1 個伺服器
2024-12-12 19:37:59 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 3.317 秒
2024-12-12 19:38:50 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 6.560 秒
2024-12-12 19:39:26 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 5.702 秒
2024-12-12 19:40:11 --> ERROR: Ignoring exception in command 'mygogif'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 245, in mygogif
    episode = result['episode']
              ~~~~~~^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygogif' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 19:40:41 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:40:41 --> INFO: logging in using static token
2024-12-12 19:40:42 --> INFO: Shard ID None has connected to Gateway (Session ID: 7604b014f1ae520f4eff36fc36b356f9).
2024-12-12 19:40:45 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:40:45 --> INFO: 伺服器狀態更新為: GO了56次 | 1 個伺服器
2024-12-12 19:40:54 --> ERROR: Ignoring exception in command 'mygogif'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 269, in mygogif
    logging.info(f"伺服器ID: {interaction.guild_id} 台詞: {result['text']} {str(duration)}秒GIF耗時: {total_seconds:.3f} 秒")
                                                           ~~~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygogif' raised an exception: TypeError: list indices must be integers or slices, not str
2024-12-12 19:41:20 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:41:20 --> INFO: logging in using static token
2024-12-12 19:41:22 --> INFO: Shard ID None has connected to Gateway (Session ID: d71d1b8fb02c1791c23501e59f11f6c4).
2024-12-12 19:41:24 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:41:24 --> INFO: 伺服器狀態更新為: GO了56次 | 1 個伺服器
2024-12-12 19:42:43 --> INFO: 伺服器ID: 762279698360172595 台詞: 小祥 1.5秒GIF耗時: 73.113 秒
2024-12-12 19:43:27 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:43:27 --> INFO: logging in using static token
2024-12-12 19:43:29 --> INFO: Shard ID None has connected to Gateway (Session ID: a5e6af388ac379b43874cc9d2c57d718).
2024-12-12 19:43:31 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:43:31 --> INFO: 伺服器狀態更新為: GO了57次 | 1 個伺服器
2024-12-12 19:43:46 --> INFO: 伺服器ID: 762279698360172595 台詞: 是這樣嗎 1.5秒GIF耗時: 10.908 秒
2024-12-12 19:44:01 --> INFO: 伺服器ID: 762279698360172595 台詞: 可是,小祥是CRYCHIC的創始者啊 耗時: 10.892 秒
2024-12-12 19:44:17 --> INFO: 伺服器ID: 762279698360172595 台詞: 沒錯 耗時: 6.145 秒
2024-12-12 19:44:28 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼要演奏春日影! 耗時: 2.384 秒
2024-12-12 19:44:36 --> INFO: 伺服器ID: 762279698360172595 台詞: 味道醇香,我很喜歡 耗時: 4.179 秒
2024-12-12 19:44:54 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 6.787 秒
2024-12-12 19:45:24 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 12.033 秒
2024-12-12 19:45:40 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 19:45:40 --> INFO: logging in using static token
2024-12-12 19:45:41 --> INFO: Shard ID None has connected to Gateway (Session ID: cbb2b9b9b390af12f9a74730ddc18e47).
2024-12-12 19:45:44 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 19:45:44 --> INFO: 伺服器狀態更新為: GO了64次 | 1 個伺服器
2024-12-12 19:45:52 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 4.731 秒
2024-12-12 19:47:08 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 1.5秒GIF耗時: 49.400 秒
2024-12-12 19:47:45 --> INFO: 伺服器ID: 762279698360172595 台詞: 是啊 耗時: 8.334 秒
2024-12-12 19:48:24 --> ERROR: Ignoring exception in command 'mygo'
Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 188, in mygo
    result = text_process_precise(text)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "g:\coding PROJECT\mygo_dc\mygo_dc\main.py", line 72, in text_process_precise
    text = json.loads(text)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\10403\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\app_commands\commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'mygo' raised an exception: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-12-12 19:49:13 --> INFO: 伺服器ID: 762279698360172595 台詞: 是嗎 耗時: 6.727 秒
2024-12-12 19:49:34 --> INFO: 伺服器ID: 762279698360172595 台詞: 是嗎 耗時: 6.947 秒
2024-12-12 19:50:03 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼? 耗時: 4.941 秒
2024-12-12 19:50:20 --> INFO: 伺服器ID: 762279698360172595 台詞: 對啊 耗時: 6.298 秒
2024-12-12 19:52:08 --> INFO: 伺服器ID: 762279698360172595 台詞: 太棒了,爽世同學LOVE 耗時: 11.369 秒
2024-12-12 20:04:45 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 20:04:45 --> INFO: logging in using static token
2024-12-12 20:04:47 --> INFO: Shard ID None has connected to Gateway (Session ID: 14e429ff5a5d2552995d594ec510700d).
2024-12-12 20:04:49 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 20:04:49 --> INFO: 伺服器狀態更新為: GO了72次 | 1 個伺服器
2024-12-12 20:05:18 --> INFO: 伺服器ID: 762279698360172595 台詞: 我沒那麼說 1.5秒GIF耗時: 8.291 秒
2024-12-12 20:06:10 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼要演奏春日影! 1.5秒GIF耗時: 29.463 秒
2024-12-12 20:06:42 --> INFO: 伺服器ID: 762279698360172595 台詞: 味道醇香,我很喜歡 1.5秒GIF耗時: 4.850 秒
2024-12-12 20:11:31 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 20:11:31 --> INFO: logging in using static token
2024-12-12 20:11:33 --> INFO: Shard ID None has connected to Gateway (Session ID: bf0c6dbaed6b2ecfb37f9344f5d6cd15).
2024-12-12 20:11:35 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 20:11:35 --> INFO: 伺服器狀態更新為: GO了75次 | 1 個伺服器
2024-12-12 20:12:00 --> INFO: 伺服器ID: 762279698360172595 台詞: 牠是阿德利企鵝屬 1.5秒GIF耗時: 11.401 秒
2024-12-12 20:12:45 --> INFO: 伺服器ID: 762279698360172595 台詞: 為什麼要演奏春日影! 1.5秒GIF耗時: 24.513 秒
2024-12-12 20:16:29 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 20:16:29 --> INFO: logging in using static token
2024-12-12 20:16:31 --> INFO: Shard ID None has connected to Gateway (Session ID: 3f46c2fc147da838c40c83e15a9de104).
2024-12-12 20:16:34 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 20:16:34 --> INFO: 伺服器狀態更新為: GO了77次 | 1 個伺服器
2024-12-12 20:16:43 --> INFO: json load : 56478
2024-12-12 20:16:54 --> INFO: json load : {"frame_start": 4136, "frame_end": 4168, "episode": "10"}
2024-12-12 20:16:56 --> INFO: 伺服器ID: 762279698360172595 台詞: 椅背壓不下去 耗時: 2.390 秒
2024-12-12 20:32:01 --> WARNING: Privileged message content intent is missing, commands may not work as expected.
2024-12-12 20:32:01 --> INFO: logging in using static token
2024-12-12 20:32:03 --> INFO: Shard ID None has connected to Gateway (Session ID: bda685b0f0ab4f33ded3f1d33996501b).
2024-12-12 20:32:05 --> INFO: 已上線: 買夠機器人(測試)#9807 | 在 1 個伺服器中
2024-12-12 20:32:05 --> INFO: 伺服器狀態更新為: GO了78次 | 1 個伺服器
2024-12-12 20:33:10 --> INFO: 伺服器ID: 762279698360172595 台詞: 妳要不要先去洗澡? 耗時: 3.943 秒
2024-12-12 20:33:27 --> INFO: 伺服器ID: 762279698360172595 台詞: "春日影"... 耗時: 3.313 秒
2024-12-12 20:33:35 --> INFO: 伺服器ID: 762279698360172595 台詞: 我要退出CRYCHIC 耗時: 3.162 秒
2024-12-12 20:33:40 --> INFO: 伺服器ID: 762279698360172595 台詞: 妳沒有來學校上課 耗時: 2.667 秒
2024-12-12 20:33:44 --> INFO: 伺服器ID: 762279698360172595 台詞: 妳終於來了 太好了 9 耗時: 2.774 秒
2024-12-12 20:33:48 --> INFO: 伺服器ID: 762279698360172595 台詞: 妳全身都濕透了,沒事吧? 耗時: 3.064 秒
2024-12-12 20:34:14 --> INFO: 伺服器ID: 762279698360172595 台詞: 傳訊息也都沒有回 1.5秒GIF耗時: 10.088 秒
2024-12-12 20:34:20 --> INFO: 伺服器ID: 762279698360172595 台詞: I055 CBanG Dream! Projeet LieansedW MuE 耗時: 3.682 秒
2024-12-12 20:47:05 --> INFO: 伺服器狀態更新為: GO了86次 | 1 個伺服器
